#define BUFFER_SIZE 1024
#define MAX_COMMANDS 10

#define PIPENAME "server_pipe"

// TASK STATUS MACROS
#define TASK_TERMINATED 0
#define TASK_RUNNING 1
#define TASK_TERMINATED_INACTIVITY 2
#define TASK_TERMINATED_EXECUTION_TIME 3
